# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 17:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20161016_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('inode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True, serialize=False, to='files.Inode')),
                ('mime', models.CharField(
                    default='application/octet-stream', max_length=256)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('files.inode',),
        ),
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True,
                                       path='/home/m157q/github/fengyuan/data/', recursive=True),
        ),
        migrations.AlterField(
            model_name='inode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
